services:
  permissions_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: permissions_service
    ports:
      - '0.0.0.0:5002:5002'
    networks:
      local_network:
        ipv4_address: 172.18.1.2
    restart: always
    depends_on:
      - postgres
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=permissions_user
      - PG_PASSWORD=permissions_password
      - PG_DBNAME=permissions_db
      - PG_SSLMODE=disable
      - PORT=5002

  postgres:
    image: postgres:15-alpine
    container_name: permissions_postgres
    environment:
      POSTGRES_DB: permissions_db
      POSTGRES_USER: permissions_user
      POSTGRES_PASSWORD: permissions_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      local_network:
        ipv4_address: 172.18.1.3
    restart: always

volumes:
  postgres_data:

networks:
  local_network:
    name: local_network
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16 