// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"permission-service/internal/app/ent/firstlogin"
	"permission-service/internal/app/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FirstLoginDelete is the builder for deleting a FirstLogin entity.
type FirstLoginDelete struct {
	config
	hooks    []Hook
	mutation *FirstLoginMutation
}

// Where appends a list predicates to the FirstLoginDelete builder.
func (fld *FirstLoginDelete) Where(ps ...predicate.FirstLogin) *FirstLoginDelete {
	fld.mutation.Where(ps...)
	return fld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fld *FirstLoginDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fld.sqlExec, fld.mutation, fld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fld *FirstLoginDelete) ExecX(ctx context.Context) int {
	n, err := fld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fld *FirstLoginDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(firstlogin.Table, sqlgraph.NewFieldSpec(firstlogin.FieldID, field.TypeInt))
	if ps := fld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fld.mutation.done = true
	return affected, err
}

// FirstLoginDeleteOne is the builder for deleting a single FirstLogin entity.
type FirstLoginDeleteOne struct {
	fld *FirstLoginDelete
}

// Where appends a list predicates to the FirstLoginDelete builder.
func (fldo *FirstLoginDeleteOne) Where(ps ...predicate.FirstLogin) *FirstLoginDeleteOne {
	fldo.fld.mutation.Where(ps...)
	return fldo
}

// Exec executes the deletion query.
func (fldo *FirstLoginDeleteOne) Exec(ctx context.Context) error {
	n, err := fldo.fld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{firstlogin.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fldo *FirstLoginDeleteOne) ExecX(ctx context.Context) {
	if err := fldo.Exec(ctx); err != nil {
		panic(err)
	}
}
