// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"permission-service/internal/app/ent/loginattempts"
	"permission-service/internal/app/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LoginAttempts is the model entity for the LoginAttempts schema.
type LoginAttempts struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int `json:"updated_by,omitempty"`
	// DeletedBy holds the value of the "deleted_by" field.
	DeletedBy *int `json:"deleted_by,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Successful holds the value of the "successful" field.
	Successful bool `json:"successful,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LoginAttemptsQuery when eager-loading is set.
	Edges        LoginAttemptsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LoginAttemptsEdges holds the relations/edges for other nodes in the graph.
type LoginAttemptsEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoginAttemptsEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LoginAttempts) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case loginattempts.FieldSuccessful:
			values[i] = new(sql.NullBool)
		case loginattempts.FieldID, loginattempts.FieldCreatedBy, loginattempts.FieldUpdatedBy, loginattempts.FieldDeletedBy, loginattempts.FieldUserID:
			values[i] = new(sql.NullInt64)
		case loginattempts.FieldCreatedAt, loginattempts.FieldUpdatedAt, loginattempts.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LoginAttempts fields.
func (la *LoginAttempts) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loginattempts.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			la.ID = int(value.Int64)
		case loginattempts.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				la.CreatedAt = value.Time
			}
		case loginattempts.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				la.UpdatedAt = value.Time
			}
		case loginattempts.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				la.DeletedAt = new(time.Time)
				*la.DeletedAt = value.Time
			}
		case loginattempts.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				la.CreatedBy = int(value.Int64)
			}
		case loginattempts.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				la.UpdatedBy = int(value.Int64)
			}
		case loginattempts.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				la.DeletedBy = new(int)
				*la.DeletedBy = int(value.Int64)
			}
		case loginattempts.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				la.UserID = int(value.Int64)
			}
		case loginattempts.FieldSuccessful:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field successful", values[i])
			} else if value.Valid {
				la.Successful = value.Bool
			}
		default:
			la.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LoginAttempts.
// This includes values selected through modifiers, order, etc.
func (la *LoginAttempts) Value(name string) (ent.Value, error) {
	return la.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the LoginAttempts entity.
func (la *LoginAttempts) QueryUser() *UserQuery {
	return NewLoginAttemptsClient(la.config).QueryUser(la)
}

// Update returns a builder for updating this LoginAttempts.
// Note that you need to call LoginAttempts.Unwrap() before calling this method if this LoginAttempts
// was returned from a transaction, and the transaction was committed or rolled back.
func (la *LoginAttempts) Update() *LoginAttemptsUpdateOne {
	return NewLoginAttemptsClient(la.config).UpdateOne(la)
}

// Unwrap unwraps the LoginAttempts entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (la *LoginAttempts) Unwrap() *LoginAttempts {
	_tx, ok := la.config.driver.(*txDriver)
	if !ok {
		panic("ent: LoginAttempts is not a transactional entity")
	}
	la.config.driver = _tx.drv
	return la
}

// String implements the fmt.Stringer.
func (la *LoginAttempts) String() string {
	var builder strings.Builder
	builder.WriteString("LoginAttempts(")
	builder.WriteString(fmt.Sprintf("id=%v, ", la.ID))
	builder.WriteString("created_at=")
	builder.WriteString(la.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(la.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := la.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", la.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", la.UpdatedBy))
	builder.WriteString(", ")
	if v := la.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", la.UserID))
	builder.WriteString(", ")
	builder.WriteString("successful=")
	builder.WriteString(fmt.Sprintf("%v", la.Successful))
	builder.WriteByte(')')
	return builder.String()
}

// LoginAttemptsSlice is a parsable slice of LoginAttempts.
type LoginAttemptsSlice []*LoginAttempts
