// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"permission-service/internal/app/ent/loginattempts"
	"permission-service/internal/app/ent/predicate"
	"permission-service/internal/app/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoginAttemptsQuery is the builder for querying LoginAttempts entities.
type LoginAttemptsQuery struct {
	config
	ctx        *QueryContext
	order      []loginattempts.OrderOption
	inters     []Interceptor
	predicates []predicate.LoginAttempts
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LoginAttemptsQuery builder.
func (laq *LoginAttemptsQuery) Where(ps ...predicate.LoginAttempts) *LoginAttemptsQuery {
	laq.predicates = append(laq.predicates, ps...)
	return laq
}

// Limit the number of records to be returned by this query.
func (laq *LoginAttemptsQuery) Limit(limit int) *LoginAttemptsQuery {
	laq.ctx.Limit = &limit
	return laq
}

// Offset to start from.
func (laq *LoginAttemptsQuery) Offset(offset int) *LoginAttemptsQuery {
	laq.ctx.Offset = &offset
	return laq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (laq *LoginAttemptsQuery) Unique(unique bool) *LoginAttemptsQuery {
	laq.ctx.Unique = &unique
	return laq
}

// Order specifies how the records should be ordered.
func (laq *LoginAttemptsQuery) Order(o ...loginattempts.OrderOption) *LoginAttemptsQuery {
	laq.order = append(laq.order, o...)
	return laq
}

// QueryUser chains the current query on the "user" edge.
func (laq *LoginAttemptsQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: laq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := laq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := laq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(loginattempts.Table, loginattempts.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, loginattempts.UserTable, loginattempts.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(laq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LoginAttempts entity from the query.
// Returns a *NotFoundError when no LoginAttempts was found.
func (laq *LoginAttemptsQuery) First(ctx context.Context) (*LoginAttempts, error) {
	nodes, err := laq.Limit(1).All(setContextOp(ctx, laq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{loginattempts.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (laq *LoginAttemptsQuery) FirstX(ctx context.Context) *LoginAttempts {
	node, err := laq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LoginAttempts ID from the query.
// Returns a *NotFoundError when no LoginAttempts ID was found.
func (laq *LoginAttemptsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = laq.Limit(1).IDs(setContextOp(ctx, laq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{loginattempts.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (laq *LoginAttemptsQuery) FirstIDX(ctx context.Context) int {
	id, err := laq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LoginAttempts entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LoginAttempts entity is found.
// Returns a *NotFoundError when no LoginAttempts entities are found.
func (laq *LoginAttemptsQuery) Only(ctx context.Context) (*LoginAttempts, error) {
	nodes, err := laq.Limit(2).All(setContextOp(ctx, laq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{loginattempts.Label}
	default:
		return nil, &NotSingularError{loginattempts.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (laq *LoginAttemptsQuery) OnlyX(ctx context.Context) *LoginAttempts {
	node, err := laq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LoginAttempts ID in the query.
// Returns a *NotSingularError when more than one LoginAttempts ID is found.
// Returns a *NotFoundError when no entities are found.
func (laq *LoginAttemptsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = laq.Limit(2).IDs(setContextOp(ctx, laq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{loginattempts.Label}
	default:
		err = &NotSingularError{loginattempts.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (laq *LoginAttemptsQuery) OnlyIDX(ctx context.Context) int {
	id, err := laq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LoginAttemptsSlice.
func (laq *LoginAttemptsQuery) All(ctx context.Context) ([]*LoginAttempts, error) {
	ctx = setContextOp(ctx, laq.ctx, ent.OpQueryAll)
	if err := laq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LoginAttempts, *LoginAttemptsQuery]()
	return withInterceptors[[]*LoginAttempts](ctx, laq, qr, laq.inters)
}

// AllX is like All, but panics if an error occurs.
func (laq *LoginAttemptsQuery) AllX(ctx context.Context) []*LoginAttempts {
	nodes, err := laq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LoginAttempts IDs.
func (laq *LoginAttemptsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if laq.ctx.Unique == nil && laq.path != nil {
		laq.Unique(true)
	}
	ctx = setContextOp(ctx, laq.ctx, ent.OpQueryIDs)
	if err = laq.Select(loginattempts.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (laq *LoginAttemptsQuery) IDsX(ctx context.Context) []int {
	ids, err := laq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (laq *LoginAttemptsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, laq.ctx, ent.OpQueryCount)
	if err := laq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, laq, querierCount[*LoginAttemptsQuery](), laq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (laq *LoginAttemptsQuery) CountX(ctx context.Context) int {
	count, err := laq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (laq *LoginAttemptsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, laq.ctx, ent.OpQueryExist)
	switch _, err := laq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (laq *LoginAttemptsQuery) ExistX(ctx context.Context) bool {
	exist, err := laq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LoginAttemptsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (laq *LoginAttemptsQuery) Clone() *LoginAttemptsQuery {
	if laq == nil {
		return nil
	}
	return &LoginAttemptsQuery{
		config:     laq.config,
		ctx:        laq.ctx.Clone(),
		order:      append([]loginattempts.OrderOption{}, laq.order...),
		inters:     append([]Interceptor{}, laq.inters...),
		predicates: append([]predicate.LoginAttempts{}, laq.predicates...),
		withUser:   laq.withUser.Clone(),
		// clone intermediate query.
		sql:  laq.sql.Clone(),
		path: laq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (laq *LoginAttemptsQuery) WithUser(opts ...func(*UserQuery)) *LoginAttemptsQuery {
	query := (&UserClient{config: laq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	laq.withUser = query
	return laq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LoginAttempts.Query().
//		GroupBy(loginattempts.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (laq *LoginAttemptsQuery) GroupBy(field string, fields ...string) *LoginAttemptsGroupBy {
	laq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LoginAttemptsGroupBy{build: laq}
	grbuild.flds = &laq.ctx.Fields
	grbuild.label = loginattempts.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.LoginAttempts.Query().
//		Select(loginattempts.FieldCreatedAt).
//		Scan(ctx, &v)
func (laq *LoginAttemptsQuery) Select(fields ...string) *LoginAttemptsSelect {
	laq.ctx.Fields = append(laq.ctx.Fields, fields...)
	sbuild := &LoginAttemptsSelect{LoginAttemptsQuery: laq}
	sbuild.label = loginattempts.Label
	sbuild.flds, sbuild.scan = &laq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LoginAttemptsSelect configured with the given aggregations.
func (laq *LoginAttemptsQuery) Aggregate(fns ...AggregateFunc) *LoginAttemptsSelect {
	return laq.Select().Aggregate(fns...)
}

func (laq *LoginAttemptsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range laq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, laq); err != nil {
				return err
			}
		}
	}
	for _, f := range laq.ctx.Fields {
		if !loginattempts.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if laq.path != nil {
		prev, err := laq.path(ctx)
		if err != nil {
			return err
		}
		laq.sql = prev
	}
	return nil
}

func (laq *LoginAttemptsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LoginAttempts, error) {
	var (
		nodes       = []*LoginAttempts{}
		_spec       = laq.querySpec()
		loadedTypes = [1]bool{
			laq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LoginAttempts).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LoginAttempts{config: laq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, laq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := laq.withUser; query != nil {
		if err := laq.loadUser(ctx, query, nodes, nil,
			func(n *LoginAttempts, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (laq *LoginAttemptsQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*LoginAttempts, init func(*LoginAttempts), assign func(*LoginAttempts, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*LoginAttempts)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (laq *LoginAttemptsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := laq.querySpec()
	_spec.Node.Columns = laq.ctx.Fields
	if len(laq.ctx.Fields) > 0 {
		_spec.Unique = laq.ctx.Unique != nil && *laq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, laq.driver, _spec)
}

func (laq *LoginAttemptsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(loginattempts.Table, loginattempts.Columns, sqlgraph.NewFieldSpec(loginattempts.FieldID, field.TypeInt))
	_spec.From = laq.sql
	if unique := laq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if laq.path != nil {
		_spec.Unique = true
	}
	if fields := laq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginattempts.FieldID)
		for i := range fields {
			if fields[i] != loginattempts.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if laq.withUser != nil {
			_spec.Node.AddColumnOnce(loginattempts.FieldUserID)
		}
	}
	if ps := laq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := laq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := laq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := laq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (laq *LoginAttemptsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(laq.driver.Dialect())
	t1 := builder.Table(loginattempts.Table)
	columns := laq.ctx.Fields
	if len(columns) == 0 {
		columns = loginattempts.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if laq.sql != nil {
		selector = laq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if laq.ctx.Unique != nil && *laq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range laq.predicates {
		p(selector)
	}
	for _, p := range laq.order {
		p(selector)
	}
	if offset := laq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := laq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LoginAttemptsGroupBy is the group-by builder for LoginAttempts entities.
type LoginAttemptsGroupBy struct {
	selector
	build *LoginAttemptsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lagb *LoginAttemptsGroupBy) Aggregate(fns ...AggregateFunc) *LoginAttemptsGroupBy {
	lagb.fns = append(lagb.fns, fns...)
	return lagb
}

// Scan applies the selector query and scans the result into the given value.
func (lagb *LoginAttemptsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lagb.build.ctx, ent.OpQueryGroupBy)
	if err := lagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoginAttemptsQuery, *LoginAttemptsGroupBy](ctx, lagb.build, lagb, lagb.build.inters, v)
}

func (lagb *LoginAttemptsGroupBy) sqlScan(ctx context.Context, root *LoginAttemptsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lagb.fns))
	for _, fn := range lagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lagb.flds)+len(lagb.fns))
		for _, f := range *lagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LoginAttemptsSelect is the builder for selecting fields of LoginAttempts entities.
type LoginAttemptsSelect struct {
	*LoginAttemptsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (las *LoginAttemptsSelect) Aggregate(fns ...AggregateFunc) *LoginAttemptsSelect {
	las.fns = append(las.fns, fns...)
	return las
}

// Scan applies the selector query and scans the result into the given value.
func (las *LoginAttemptsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, las.ctx, ent.OpQuerySelect)
	if err := las.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoginAttemptsQuery, *LoginAttemptsSelect](ctx, las.LoginAttemptsQuery, las, las.inters, v)
}

func (las *LoginAttemptsSelect) sqlScan(ctx context.Context, root *LoginAttemptsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(las.fns))
	for _, fn := range las.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*las.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := las.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
