// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"permission-service/internal/app/ent/permission"
	"permission-service/internal/app/ent/services"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServicesCreate is the builder for creating a Services entity.
type ServicesCreate struct {
	config
	mutation *ServicesMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (sc *ServicesCreate) SetCreatedAt(t time.Time) *ServicesCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *ServicesCreate) SetNillableCreatedAt(t *time.Time) *ServicesCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *ServicesCreate) SetUpdatedAt(t time.Time) *ServicesCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *ServicesCreate) SetNillableUpdatedAt(t *time.Time) *ServicesCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetDeletedAt sets the "deleted_at" field.
func (sc *ServicesCreate) SetDeletedAt(t time.Time) *ServicesCreate {
	sc.mutation.SetDeletedAt(t)
	return sc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sc *ServicesCreate) SetNillableDeletedAt(t *time.Time) *ServicesCreate {
	if t != nil {
		sc.SetDeletedAt(*t)
	}
	return sc
}

// SetCreatedBy sets the "created_by" field.
func (sc *ServicesCreate) SetCreatedBy(i int) *ServicesCreate {
	sc.mutation.SetCreatedBy(i)
	return sc
}

// SetUpdatedBy sets the "updated_by" field.
func (sc *ServicesCreate) SetUpdatedBy(i int) *ServicesCreate {
	sc.mutation.SetUpdatedBy(i)
	return sc
}

// SetDeletedBy sets the "deleted_by" field.
func (sc *ServicesCreate) SetDeletedBy(i int) *ServicesCreate {
	sc.mutation.SetDeletedBy(i)
	return sc
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (sc *ServicesCreate) SetNillableDeletedBy(i *int) *ServicesCreate {
	if i != nil {
		sc.SetDeletedBy(*i)
	}
	return sc
}

// SetName sets the "name" field.
func (sc *ServicesCreate) SetName(s string) *ServicesCreate {
	sc.mutation.SetName(s)
	return sc
}

// AddPermissionIDs adds the "permission" edge to the Permission entity by IDs.
func (sc *ServicesCreate) AddPermissionIDs(ids ...int) *ServicesCreate {
	sc.mutation.AddPermissionIDs(ids...)
	return sc
}

// AddPermission adds the "permission" edges to the Permission entity.
func (sc *ServicesCreate) AddPermission(p ...*Permission) *ServicesCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddPermissionIDs(ids...)
}

// Mutation returns the ServicesMutation object of the builder.
func (sc *ServicesCreate) Mutation() *ServicesMutation {
	return sc.mutation
}

// Save creates the Services in the database.
func (sc *ServicesCreate) Save(ctx context.Context) (*Services, error) {
	if err := sc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *ServicesCreate) SaveX(ctx context.Context) *Services {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *ServicesCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *ServicesCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *ServicesCreate) defaults() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		if services.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized services.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := services.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		if services.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized services.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := services.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (sc *ServicesCreate) check() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Services.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Services.updated_at"`)}
	}
	if _, ok := sc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Services.created_by"`)}
	}
	if v, ok := sc.mutation.CreatedBy(); ok {
		if err := services.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "Services.created_by": %w`, err)}
		}
	}
	if _, ok := sc.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "Services.updated_by"`)}
	}
	if v, ok := sc.mutation.UpdatedBy(); ok {
		if err := services.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "Services.updated_by": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Services.name"`)}
	}
	if v, ok := sc.mutation.Name(); ok {
		if err := services.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Services.name": %w`, err)}
		}
	}
	return nil
}

func (sc *ServicesCreate) sqlSave(ctx context.Context) (*Services, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *ServicesCreate) createSpec() (*Services, *sqlgraph.CreateSpec) {
	var (
		_node = &Services{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(services.Table, sqlgraph.NewFieldSpec(services.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(services.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(services.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.DeletedAt(); ok {
		_spec.SetField(services.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := sc.mutation.CreatedBy(); ok {
		_spec.SetField(services.FieldCreatedBy, field.TypeInt, value)
		_node.CreatedBy = value
	}
	if value, ok := sc.mutation.UpdatedBy(); ok {
		_spec.SetField(services.FieldUpdatedBy, field.TypeInt, value)
		_node.UpdatedBy = value
	}
	if value, ok := sc.mutation.DeletedBy(); ok {
		_spec.SetField(services.FieldDeletedBy, field.TypeInt, value)
		_node.DeletedBy = &value
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(services.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := sc.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   services.PermissionTable,
			Columns: []string{services.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ServicesCreateBulk is the builder for creating many Services entities in bulk.
type ServicesCreateBulk struct {
	config
	err      error
	builders []*ServicesCreate
}

// Save creates the Services entities in the database.
func (scb *ServicesCreateBulk) Save(ctx context.Context) ([]*Services, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Services, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServicesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *ServicesCreateBulk) SaveX(ctx context.Context) []*Services {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *ServicesCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *ServicesCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
